### ISSUE TITLE
GestureRecognizer on SpecialTextSpan doesn't work beneath large ExtendedWidgetSpans

### ISSUE THREAD

**Issue by Zarainia** [fluttercandies/extended_text_field#131]
See this example: 

```dart
import 'package:extended_text_field/extended_text_field.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MySpecialTextSpanBuilder extends SpecialTextSpanBuilder {
  var text_style = TextStyle(color: Colors.black);

  MySpecialTextSpanBuilder();

  @override
  TextSpan build(String data, {TextStyle? textStyle, onTap}) {
    return SpecialTextSpan(
      text: '',
      actualText: '',
      children: [
        SpecialTextSpan(text: '\n', actualText: ''),
        SpecialTextSpan(text: 'click\n', actualText: '', recognizer: TapGestureRecognizer()..onTap = () => print("clicked!"), style: text_style),
        ExtendedWidgetSpan(
          child: Container(
            height: 1000,
            color: Colors.red,
          ),
          actualText: '',
        ),
        SpecialTextSpan(text: '\nclick', actualText: '', recognizer: TapGestureRecognizer()..onTap = () => print("clicked!"), style: text_style),
      ],
    );
  }

  @override
  SpecialText? createSpecialText(String flag, {TextStyle? textStyle, SpecialTextGestureTapCallback? onTap, required int index}) {}
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text("Test"),
        ),
        body: Column(
          children: [
            Expanded(
                child: Container(
              color: Colors.blue,
            )),
            Expanded(
                child: ExtendedTextField(
              minLines: null,
              maxLines: null,
              expands: true,
              textAlignVertical: TextAlignVertical.top,
              keyboardType: TextInputType.multiline,
              specialTextSpanBuilder: MySpecialTextSpanBuilder(),
            ))
          ],
        ), // This trailing comma makes auto-formatting nicer for build methods.
      ),
    );
  }
}
```

Clicking on the 'click' SpecialTextSpan above the big red box works and prints 'clicked' in the console, but clicking on the one below it doesn't (and the mouse cursor also doesn't change when hovering over it). For some reason, both cause this error to be logged when clicked:

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'dart:ui/text.dart': Failed assertion: line 2714 pos 15: '<optimized out>': is not true.

When the exception was thrown, this was the stack: 
#2      new TextRange (dart:ui/text.dart:2714:15)
#3      new TextSelection (package:flutter/src/services/text_editing.dart:22:8)
#4      ExtendedTextSelectionRenderObject.selectPositionAt (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:279:42)
#5      ExtendedTextSelectionRenderObject.selectPosition (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:247:5)
#6      CommonTextSelectionGestureDetectorBuilder.onSingleTapUp (package:extended_text_library/src/selection/extended_text_selection.dart:470:26)
...
Handler: "onTapUp"
Recognizer: _TransparentTapGestureRecognizer#52702
  debugOwner: _TextSelectionGestureDetectorState#a225b
  state: ready
  won arena
  finalPosition: Offset(9.0, 997.0)
  finalLocalPosition: Offset(9.0, 464.5)
  button: 1
  sent tap down
====================================================================================================
```

However, as the problem only occurs with the lower clickable SpecialTextSpan, and both SpecialTextSpan produce the error, maybe it's not part of the problem. 

Platform is Windows desktop.

**Comment by zmtzawqlp** [comment]
please check it in latest version

**Comment by Zarainia** [comment]
I'm still unable to click on the gesture recognizer text and get this error when clicking on the lower 'click' SpecialTextSpan:

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'dart:ui/text.dart': Failed assertion: line 2749 pos 15: '<optimized out>': is not true.

When the exception was thrown, this was the stack: 
#2      new TextRange (dart:ui/text.dart:2749:15)
#3      new TextSelection (package:flutter/src/services/text_editing.dart:22:8)
#4      ExtendedTextSelectionRenderObject.selectPositionAt (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:280:42)
#5      ExtendedTextSelectionRenderObject.selectPosition (package:extended_text_library/src/render_object/extended_text_selection_render_object.dart:248:5)
#6      CommonTextSelectionGestureDetectorBuilder.onSingleTapUp (package:extended_text_library/src/selection/extended_text_selection.dart:470:26)
#7      _TextSelectionGestureDetectorState._handleTapUp (package:flutter/src/widgets/text_selection.dart:1398:29)
#8      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:606:57)
#9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:606:11)
#11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#24     _invoke1 (dart:ui/hooks.dart:169:10)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTapUp"
Recognizer: TapGestureRecognizer#7c3b4
  debugOwner: _TextSelectionGestureDetectorState#bd48c
  state: ready
  won arena
  finalPosition: Offset(17.0, 957.0)
  finalLocalPosition: Offset(17.0, 424.5)
  button: 1
  sent tap down
====================================================================================================
```

**Comment by zmtzawqlp** [comment]
fix with 9.0.3

**Comment by zmtzawqlp** [comment]
and take care of actualText and start of SpecialText, it's refer to selection

**Comment by Zarainia** [comment]
Looks good, thanks. 

> and take care of actualText and start of SpecialText, it's refer to selection

Is there any need to add both `start` and `actualText`? I have been able to have selection working fine with just `actualText`. `start` is more difficult to keep track of.

**Comment by zmtzawqlp** [comment]
> Looks good, thanks.
> 
> > and take care of actualText and start of SpecialText, it's refer to selection
> 
> Is there any need to add both `start` and `actualText`? I have been able to have selection working fine with just `actualText`. `start` is more difficult to keep track of.

please double click demo, if you give wrong start value, copy ,cut will get error string
