### ISSUE TITLE
[Bug report] '!composingRange.isValid || composingRange.isCollapsed': is not true

### ISSUE THREAD

**Issue by Geparder** [fluttercandies/extended_text_field#200]
### Version

11.0.1

### Platforms

Android

### Device Model

Emulator

### flutter info

```sh
When I move the carriage to the end of the text, where there is an Extended WidgetSpan, an error occurs:

Failed assertion: line 2551 pos 16: '!composingRange.isValid || composingRange.isCollapsed': is not true.
```

### How to reproduce?

There are several ExtendedWidgetSpans in the text. I click on the screen and translate courses to the end of the text.

Example:

This is an example of text with {item1} and  {item2}. And I click here.

### Logs

```sh
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:extended_text_field/src/extended_editable_text.dart': Failed assertion: line 2551 pos 16: '!composingRange.isValid || composingRange.isCollapsed': is not true.

When the exception was thrown, this was the stack: 
#2      ExtendedEditableTextState._updateComposingRectIfNeeded (package:extended_text_field/src/extended_editable_text.dart:2551:16)
#3      ExtendedEditableTextState._updateComposingRectIfNeeded.<anonymous closure> (package:extended_text_field/src/extended_editable_text.dart:2559:49)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#10     _invoke (dart:ui/hooks.dart:147:10)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#12     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 5 frames from class _AssertionError and dart:async)
```

**Comment by zmtzawqlp** [comment]
any runnable simple demo?

**Comment by Geparder** [comment]
This error is reproduced by the example attached in this repository.
https://drive.google.com/file/d/1efq6sTkB8qkYKc0Hb5WFDnC1mJUfJXIU/view?usp=sharing

**Comment by zmtzawqlp** [comment]
"extended_text_field" from pub.dev, specifically version 12.0.0, which claims to have synchronized the official code. Please give it a try, and if you still encounter issues, feel free to reopen it.

**Comment by Geparder** [comment]
In version 12.0.0 the error is repeated

**Comment by zmtzawqlp** [comment]
can you reprduce it at a really  smartphone?  i can't reproduce it at my side.

**Comment by Geparder** [comment]
The error is not repeated on a real device. Only on a virtual machine. Thank you!

**Comment by Evenjine** [comment]
> The error is not repeated on a real device. Only on a virtual machine. Thank you!

This error is caused by an assert keyword. In development and debugging, if the condition inside the assert is not true, it will trigger an exception. a temporary solution is to comment out the assert line.

open the Editable_text.dart and comment out this line:
//assert(!composingRange.isValid || composingRange.isCollapsed);
