### ISSUE TITLE
[Bug report] iOS17, 键盘切换 crash

### ISSUE THREAD

**Issue by zhoupeiyu** [fluttercandies/extended_text_field#225]
### Version

extended_text_field 12.1.0 

### Platforms

iOS

### Device Model

iOS 17

### flutter info

```sh
#0 ExtendedRenderEditable.plainText (package:extended_text_field/src/extended/rendering/editable.dart:80)
1
#1 _TextSelectionOverlay._getStartGlyphHeight (package:extended_text_field/src/official/widgets/text_selection.dart:320)
2
#2 _TextSelectionOverlay._updateSelectionOverlay (package:extended_text_field/src/official/widgets/text_selection.dart:243)
3
#3 _TextSelectionOverlay.update (package:extended_text_field/src/official/widgets/text_selection.dart:227)
4
#4 _EditableTextState._updateOrDisposeSelectionOverlayIfNeeded (package:extended_text_field/src/official/widgets/editable_text.dart:3136)
5
#5 _EditableTextState._didChangeTextEditingValue (package:extended_text_field/src/official/widgets/editable_text.dart:3608)
6
#6 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403)
7
#7 ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:530)
8
#8 TextEditingController.value= (package:flutter/src/widgets/editable_text.dart:240)
9
#9 TextEditingController.clear (package:flutter/src/widgets/editable_text.dart:311)
10
#10 ChatModel.startSendMessage (package:chatai/chat/model/chat_model.dart:259)
11
#11 ChatState._sendMessageBtn.<anonymous closure>.<anonymous closure> (package:chatai/chat/page/chat_detail_page.dart:381)
12
#12 _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
13
#13 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
14
#14 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654)
15
#15 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311)
16
#16 BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244)
17
#17 PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630)
18
#18 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
19
#19 PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
20
#20 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625)
21
#21 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
22
#22 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
23
#23 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488)
24
#24 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
25
#25 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333)
26
#26 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
27
#27 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
28
#28 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
29
#29 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
30
#30 _rootRunUnary (dart:async/zone.dart:1415)
31
#31 _CustomZone.runUnary (dart:async/zone.dart:1308)
32
#32 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
33
#33 _invoke1 (dart:ui/hooks.dart:188)
34
#34 PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424)
35
#35 _dispatchPointerDataPacket (dart:ui/hooks.dart:119)
```

### How to reproduce?

iOS 17 必现

**Comment by zmtzawqlp** [comment]
官方输入框有这个问题吗

**Comment by missyangliyuan** [comment]
这个问题有解吗？

**Comment by zmtzawqlp** [comment]
flutter 已经修复了。等下一个stable 吧
