### ISSUE TITLE
extended_text_field: 11.0.1-ohos 分支在OHOS 上光标不能位置，不能切换

### ISSUE THREAD

**Issue by wyqdcp2016** [fluttercandies/extended_text_field#254]
extended_text_field: 11.0.1-ohos 分支在OHOS 上光标不能位置，不能切换

**Comment by wyqdcp2016** [comment]
错误信息：When the exception was thrown, this was the stack:
#0 PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:295:7)
#1 AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:731:35)
#2 AssetBundleImageProvider.loadBuffer (package:flutter/src/painting/image_provider.dart:695:14)
#3 ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
#4 ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
#5 ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
#6 ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#7 ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)

**Comment by wyqdcp2016** [comment]
麻烦修改，非常感谢

**Comment by wyqdcp2016** [comment]
extended_text_field: 11.0.1-ohos 分支在OHOS 上光标 不能切换

**Comment by wyqdcp2016** [comment]
日志提示获取资源出错。就是点击光标的位置。麻烦看一下，非常感谢

**Comment by wyqdcp2016** [comment]
日志与issue 有关系

**Comment by zmtzawqlp** [comment]
为什么有关系？imageProvider 为啥跟输入框有关系？图片为什么会跟输入框有关系？
