### ISSUE TITLE
报错，导致文本框文字也不显示。

### ISSUE THREAD

**Issue by minr** [fluttercandies/extended_text_field#42]
```log
2019-12-14 21:03:41.143437+0700 七组鹅[7636:1854954] flutter: The following assertion was thrown during paint():
2019-12-14 21:03:41.143466+0700 七组鹅[7636:1854954] flutter: 'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
2019-12-14 21:03:41.143489+0700 七组鹅[7636:1854954] flutter:
2019-12-14 21:03:41.143513+0700 七组鹅[7636:1854954] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2019-12-14 21:03:41.143539+0700 七组鹅[7636:1854954] flutter: more information in this error message to help you determine and fix the underlying cause.
2019-12-14 21:03:41.143559+0700 七组鹅[7636:1854954] flutter: In either case, please report this assertion by filing a bug on GitHub:
2019-12-14 21:03:41.143579+0700 七组鹅[7636:1854954] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2019-12-14 21:03:41.144037+0700 七组鹅[7636:1854954] flutter:
2019-12-14 21:03:41.144605+0700 七组鹅[7636:1854954] flutter: The relevant error-causing widget was:
2019-12-14 21:03:41.144635+0700 七组鹅[7636:1854954] flutter:   _Editable-[GlobalKey#6077e]
2019-12-14 21:03:41.144661+0700 七组鹅[7636:1854954] flutter:   file:///Users/min/.pub-cache/hosted/pub.dartlang.org/extended_text_field-0.4.6/lib/src/extended_editable_text.dart:1552:20
2019-12-14 21:03:41.144685+0700 七组鹅[7636:1854954] flutter:
2019-12-14 21:03:41.144708+0700 七组鹅[7636:1854954] flutter: When the exception was thrown, this was the stack:
2019-12-14 21:03:41.144728+0700 七组鹅[7636:1854954] flutter: #2      new TextPosition (dart:ui/text.dart:1372:15)
2019-12-14 21:03:41.144824+0700 七组鹅[7636:1854954] flutter: #3      ExtendedRenderEditable._updateSelectionExtentsVisibility (package:extended_text_field/src/extended_render_editable.dart:283:7)
2019-12-14 21:03:41.144965+0700 七组鹅[7636:1854954] flutter: #4      ExtendedRenderEditable._paintContents (package:extended_text_field/src/extended_render_editable.dart:1871:7)
2019-12-14 21:03:41.145030+0700 七组鹅[7636:1854954] flutter: #5      ExtendedRenderEditable.paint (package:extended_text_field/src/extended_render_editable.dart:1930:7)
2019-12-14 21:03:41.145148+0700 七组鹅[7636:1854954] flutter: #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.145207+0700 七组鹅[7636:1854954] flutter: #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
2019-12-14 21:03:41.145339+0700 七组鹅[7636:1854954] flutter: #8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
2019-12-14 21:03:41.145411+0700 七组鹅[7636:1854954] flutter: #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.145505+0700 七组鹅[7636:1854954] flutter: #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
2019-12-14 21:03:41.145603+0700 七组鹅[7636:1854954] flutter: #11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
2019-12-14 21:03:41.145678+0700 七组鹅[7636:1854954] flutter: #12     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
2019-12-14 21:03:41.145798+0700 七组鹅[7636:1854954] flutter: #13     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4796:13)
2019-12-14 21:03:41.145976+0700 七组鹅[7636:1854954] flutter: #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.146099+0700 七组鹅[7636:1854954] flutter: #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
2019-12-14 21:03:41.146241+0700 七组鹅[7636:1854954] flutter: #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
2019-12-14 21:03:41.146346+0700 七组鹅[7636:1854954] flutter: #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.146458+0700 七组鹅[7636:1854954] flutter: #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
2019-12-14 21:03:41.146609+0700 七组鹅[7636:1854954] flutter: #19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
2019-12-14 21:03:41.146681+0700 七组鹅[7636:1854954] flutter: #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.146779+0700 七组鹅[7636:1854954] flutter: #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
2019-12-14 21:03:41.146967+0700 七组鹅[7636:1854954] flutter: #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
2019-12-14 21:03:41.147098+0700 七组鹅[7636:1854954] flutter: #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.147235+0700 七组鹅[7636:1854954] flutter: #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
2019-12-14 21:03:41.147372+0700 七组鹅[7636:1854954] flutter: #25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
2019-12-14 21:03:41.147474+0700 七组鹅[7636:1854954] flutter: #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.147630+0700 七组鹅[7636:1854954] flutter: #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
2019-12-14 21:03:41.147760+0700 七组鹅[7636:1854954] flutter: #28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
2019-12-14 21:03:41.147878+0700 七组鹅[7636:1854954] flutter: #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
2019-12-14 21:03:41.147970+0700 七组鹅[7636:1854954] flutter: #30     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
```

flutter version

```shell
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/min/flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

**Comment by zmtzawqlp** [comment]
请提供demo

**Comment by kinling** [comment]
升级后遇到同样问题，是在CustomScrollView和ListView中使用的时候，android报错ios正常。
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
示例代码：
CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: ExtendedTextField(
                controller: _titleController,
                maxLines: 2,
                decoration: InputDecoration(
                    hintText:  "标题",
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.only(top: 0, bottom: 0)
                ),
                style: TextStyle(
                    color: Colors.black87,
                    fontSize: 18,
                    textBaseline: TextBaseline.alphabetic
                ),
              ),
            ),
          ],
        )

**Comment by kinling** [comment]
@zmtzawqlp 升级后遇到同样问题，是在CustomScrollView和ListView中使用的时候，android报错ios正常。
'dart:ui/text.dart': Failed assertion: line 1372: '': is not true.
示例代码：
`CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: ExtendedTextField(
                controller: _titleController,
                maxLines: 2,
                decoration: InputDecoration(
                    hintText:  "标题",
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.only(top: 0, bottom: 0)
                ),
                style: TextStyle(
                    color: Colors.black87,
                    fontSize: 18,
                    textBaseline: TextBaseline.alphabetic
                ),
              ),
            ),
          ],
        )`

**Comment by kinling** [comment]
@zmtzawqlp 升级后遇到同样问题，是在CustomScrollView和ListView中使用的时候，android报错ios正常。
'dart:ui/text.dart': Failed assertion: line 1372: '': is not true.
示例代码：

> CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: ExtendedTextField(
                controller: _titleController,
                maxLines: 2,
                decoration: InputDecoration(
                    hintText:  "标题",
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.only(top: 0, bottom: 0)
                ),
                style: TextStyle(
                    color: Colors.black87,
                    fontSize: 18,
                    textBaseline: TextBaseline.alphabetic
                ),
              ),
            ),
          ],
        )

**Comment by kinling** [comment]
@zmtzawqlp 升级后遇到同样问题，是在CustomScrollView和ListView中使用的时候，android报错ios正常。
'dart:ui/text.dart': Failed assertion: line 1372: '': is not true.
示例代码：

```CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: ExtendedTextField(
                controller: _titleController,
                maxLines: 2,
                decoration: InputDecoration(
                    hintText:  "标题",
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.only(top: 0, bottom: 0)
                ),
                style: TextStyle(
                    color: Colors.black87,
                    fontSize: 18,
                    textBaseline: TextBaseline.alphabetic
                ),
              ),
            ),
          ],
        )

**Comment by kinling** [comment]
@zmtzawqlp  用你们官方的example也是同样的问题
Flutter 1.12.13+hotfix.5
Dart 2.7.0
Android 6.0.1
iphone11 pro max 模拟器

**Comment by zmtzawqlp** [comment]
相同 https://github.com/fluttercandies/extended_text_field/issues/46
